POST http://127.0.0.1:3000/auth/register
Content-Type: application/json

{
    "name": "JOEL ROSERO",
    "email": "joelrosero672@gmail.com",
    "password": "123456789"
}

### login sin conexion a DB 
POST http://127.0.0.1:3000/auth/login
Content-Type: application/json

{
    "name": "JOEL ROSERO",
    "email": "joelrosero672@gmail.com",
    "password": "123456789"
}

### users
GET http://127.0.0.1:3000/users




    